### PR TITLE
Rebuild jmespath 0.9.2 as noarch

### PR DESCRIPTION
**Pull request by xylar**
Needed downstream by [globus-cli](https://github.com/conda-forge/globus-cli-feedstock), which currently doesn't work with python 3.7

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@pmlandwehr, if you are willing to add me as a maintainer, I will immediately revert these changes.  If you prefer, you can create a new branch (e.g. `0.9.2`) on `conda-forge/jmespath-feedstock` and change the destination of this PR to that branch.  In the latter case, after merging the PR, the packages will be built and uploaded but the recipe will remain unchanged in `master` (and I will not be added as a maintainer, which is fine).

**Comment by pmlandwehr** [comment]
Hey @xylar, I can certainly add you as a maintainer. However, the standard way to handle updating old versions of packages is by creating a version-specific fork and then making the change. I'll take care of that here.

**Comment by pmlandwehr** [comment]
@xylar and thanks for your attention!

**Comment by xylar** [comment]
@pmlandwehr, thanks for creating the v0.9.2 branch.  That's exactly what I meant.  It would have been possible to change the base of this PR to be the v0.9.2 branch and then merge, but what you did is fine, too.

Closing this PR because it has already been merged implicitly into v0.9.2

**Pull request closed without merging**
